// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at
`

type CreateCourseParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

type CreateCourseRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error) {
	row := q.db.QueryRowContext(ctx, createCourse, arg.Title, arg.Description)
	var i CreateCourseRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, title, description, created_at
  FROM courses
 WHERE id = $1
`

type GetCourseRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetCourse(ctx context.Context, id int64) (GetCourseRow, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, title, description, created_at
  FROM courses
 ORDER BY created_at DESC
 LIMIT $1 OFFSET $2
`

type ListCoursesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCoursesRow struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesRow
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
