// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package db

import (
	"context"
	"database/sql"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (course_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, course_id, title, description, created_at
`

type CreateLessonParams struct {
	CourseID    int64          `json:"course_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, createLesson, arg.CourseID, arg.Title, arg.Description)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT id, course_id, title, description, created_at
  FROM lessons
 WHERE course_id = $1
 ORDER BY created_at
`

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID int64) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
