// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
)

const joinCourse = `-- name: JoinCourse :exec
INSERT INTO course_members(user_id, course_id)
VALUES ($1, $2)
`

type JoinCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) JoinCourse(ctx context.Context, arg JoinCourseParams) error {
	_, err := q.db.ExecContext(ctx, joinCourse, arg.UserID, arg.CourseID)
	return err
}

const listCourseMembers = `-- name: ListCourseMembers :many
SELECT user_id, course_id, joined_at
  FROM course_members
 WHERE course_id = $1
 ORDER BY joined_at
`

func (q *Queries) ListCourseMembers(ctx context.Context, courseID int64) ([]CourseMember, error) {
	rows, err := q.db.QueryContext(ctx, listCourseMembers, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseMember
	for rows.Next() {
		var i CourseMember
		if err := rows.Scan(&i.UserID, &i.CourseID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
