// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Course struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Price       int32          `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
}

type CourseMember struct {
	UserID   int64     `json:"user_id"`
	CourseID int64     `json:"course_id"`
	JoinedAt time.Time `json:"joined_at"`
}

type Lesson struct {
	ID          int64          `json:"id"`
	CourseID    int64          `json:"course_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
}
