// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCourse(ctx context.Context, id int64) (GetCourseRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	JoinCourse(ctx context.Context, arg JoinCourseParams) error
	ListCourseMembers(ctx context.Context, courseID int64) ([]CourseMember, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error)
	ListLessonsByCourse(ctx context.Context, courseID int64) ([]Lesson, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
